# Generated by Django 4.2.6 on 2023-10-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomeUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=120)),
                ('cel', models.IntegerField()),
                ('email', models.TextField(max_length=40)),
                ('cpf', models.IntegerField()),
                ('estado_civil', models.TextField(max_length=40)),
                ('genero', models.TextField(max_length=40)),
                ('rua', models.TextField(max_length=80)),
                ('complemento', models.TextField(max_length=40)),
                ('cidade', models.TextField(max_length=40)),
                ('estado', models.TextField(max_length=40)),
                ('cep', models.TextField(max_length=40)),
            ],
        ),
    ]
