# Generated by Django 4.2.6 on 2023-10-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomeusuario',
            name='cep',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='cidade',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='complemento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='estado',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='estado_civil',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='genero',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='rua',
            field=models.CharField(max_length=80),
        ),
    ]
