# Generated by Django 4.2.6 on 2023-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_nomeusuario_cep_alter_nomeusuario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomeusuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'solteiro'), ('casado', 'casado'), ('viuvo', 'viuvo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='nomeusuario',
            name='genero',
            field=models.CharField(choices=[('masculino', 'masculino'), ('feminino', 'feminino'), ('outros', 'outros')], max_length=40),
        ),
    ]
